services:
  db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d catalog" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    image: es.bdo/skeleton:0.0.1
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./src/main/resources/db/migration:/workspace/migration:ro
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
    networks:
      - backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  auth:
    image: ghcr.io/zitadel/zitadel:v4.11.0
    command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters"
    depends_on:
      db:
        condition: service_healthy
    env_file: .zitadel.env
    volumes:
      - auth_data:/current-dir:delegated
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend
    ports:
      - "8081:8081"
      - "3000:3000"
    restart: unless-stopped

  login:
    image: ghcr.io/zitadel/zitadel-login:v4.11.0
    depends_on:
      auth:
        condition: service_healthy
        restart: false
    env_file: .login.env
    volumes:
      - auth_data:/current-dir:ro
    network_mode: service:auth
    restart: unless-stopped

volumes:
  auth_data:
  db_data:

networks:
  backend:
